name: Lux Coast
favicon: null
layout_spectrum: 0.5559980373363942
typography_spectrum: 0.6701117085758597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.14575746236369014
  lightness: 0.09207205730490386
  saturation: 0.08985897316597402
  rhythmicContrast: 0.9081529499962926
purpose: []
